### ISSUE TITLE
Issue with solana-swap python API #2

### ISSUE THREAD

**Issue by neochine** [YZYLAB/solana-swap-python#2]
Not sure if its a bug or intended like that but confirm_transaction doesn't seem to be confirming transactions actually. Its just checking with retries until it gets confirmed and returning txid.
```
    def confirm_transaction(self, txid: str, max_retries: int = 60, retry_interval: float = 1.0) -> str:
        retries = 0
        while retries < max_retries:
            try:
                resp = self.connection.get_signature_statuses([Signature.from_string(txid)], True)
                if resp.value is not None and len(resp.value) > 0:
                    if self.debug and resp.value[0] is not None and resp.value[0].confirmations:
                        print(f"Confirmations: {resp.value[0].confirmations}")
                    if resp.value[0] is not None and resp.value[0].confirmation_status is not None and str(resp.value[0].confirmation_status) == "TransactionConfirmationStatus.Finalized":
                        break
            except Exception as e:
                print(f"Error checking transaction status: {e}")
            retries += 1
            time.sleep(retry_interval)
        if retries >= max_retries:
            raise TimeoutError(f"Transaction {txid} was not confirmed after {max_retries} retries")
        else:
            return txid
```
It makes sense to rename this function to something like wait_until_transaction_confirmation or wait_with_retry_until_transaction_confirmation (name is too long but someone could think better name). And instead of returning str/txid on pass and Exception on fail, perhaps it would be better to return True or False. True when it gets confirmed and False when transaction fails to confirm even after x number of retires? This is just a suggestion rather than actual bug. `retry` library from pip might also simplify logic

**Comment by neochine** [comment]
Further improvement could be done by adding setup.py and setup.cfg so its easily installable instead of git cloning and using as imports

**Comment by YZYLAB** [comment]
_"Not sure if its a bug or intended like that but confirm_transaction doesn't seem to be confirming transactions actually. Its just checking with retries until it gets confirmed and returning txid."_ 

Solana confirms the transaction. You can't confirm the transaciton yourself. So yes it's correct that it retries and waits till the it enough confirmations. 

"Further improvement could be done by adding setup.py and setup.cfg so its easily installable instead of git cloning and using as imports" 

I will have a look at this, I don't usually code in Python so will have to take a look haha. 

Thanks for the suggestions!
